### ISSUE TITLE
Too big vibrator

### ISSUE THREAD

**Issue by EERCrso** [vtothsvk/AP-Home#10]
**Describe the bug**
The vibrator  in bracellet watch is huge

**To Reproduce**
look at the vibrator

**Expected behavior**
to be smaller  so the box can be closed

**Comment by xosuskyf** [comment]
see https://github.com/vtothsvk/AP-Home/issues/27

**Comment by EERCrso** [comment]
According the  issue was fixed

**Comment by EERCrso** [comment]
done
