### ISSUE TITLE
light sensor is exposed outside of the box

### ISSUE THREAD

**Issue by EERCrso** [vtothsvk/AP-Home#16]
**Describe the bug**
light sensor is exposed outside of the box hide it

![image](https://user-images.githubusercontent.com/66819699/98517321-045eca00-226e-11eb-9a5b-8b3571686e90.png)

**Comment by xmirob** [comment]
Wire length need to be reduced.

**Comment by xosuskyf** [comment]
see comment in https://github.com/vtothsvk/AP-Home/issues/65

**Comment by EERCrso** [comment]
presunute do https://github.com/vtothsvk/AP-Home/issues/65
