### ISSUE TITLE
Gas sensors in not stable possition

### ISSUE THREAD

**Issue by EERCrso** [vtothsvk/AP-Home#19]
**Describe the bug**
whet applying pressure on the outside part of GAS sensors the sensors are pushed back into the box, and due to small opening in the case they can but bushed back only with extra force, witch can lead to breaking of the box

**Comment by xmirob** [comment]
We should meet and test this issue together, because, in my case it is stable.

**Comment by EERCrso** [comment]
ked ich zatlačim dovnutra tak sa vcucnu.. ked to spadne na zem z boku tak sa zatlačia .. skus

**Comment by xmirob** [comment]
Musia sa zatlačiť na doraz, potom, sedia správne a držia pevne. Ak boli nedostatočne zasunuté ako na fotografií, potom je to chyba nedostatočného zasunutia. Ide to však ťažko a hrozí zlomenie stredového predelu medzi otvormi, do modelu V4 som preto spravil o 0,1mm väčšie otvory.

**Comment by xosuskyf** [comment]
It depends on material. In the case of PLA string material, I needed to enlarge little bit both holes on gas and smoke sensor  just to be able to fit them into the holes. In this material, the sensors are very stable.

**Comment by EERCrso** [comment]
RIESENIE HOT GLUE
