### ISSUE TITLE
buzzer in not stable possition

### ISSUE THREAD

**Issue by EERCrso** [vtothsvk/AP-Home#21]
**Describe the bug**
whet applying pressure on the outside part of buzzer the buzzer is pushed back into the box

**Comment by xmirob** [comment]
Hole will be optimized in version 4.

**Comment by xmirob** [comment]
Diameter of the hole was reduced in the V4 model. Glue will be necessary to apply to fix the buzzer properly. In the final version, buzzer need to be mounted on the base PCB.

**Comment by EERCrso** [comment]
RIESENIE HOT GLUE
