### ISSUE TITLE
No day night switch

### ISSUE THREAD

**Issue by EERCrso** [vtothsvk/AP-Home#23]
**Describe the bug**
There is no day night switch.

**Comment by mato24101** [comment]
Day night switch je vo fáze že 10ks máme u nás vkancelárií a bolo by prípadne dobré overiť či sa dokáže vmestiť do krabičky spolu s ostatnými vecami ktoré sa tam už nachádzajú. Prípadne ak sa nezmestia bol oby dobré vybrať iný dizajn prepínaču a následne možno upraviť aj krabičku (najme sa bavíme o uchytení a otvore pre prepínač). Zatial máme nakúpené tieto prepínače https://www.gme.sk/packovy-spinac-smts-102

**Comment by EERCrso** [comment]
rovno to dajme teda mirovi ne ?

**Comment by xosuskyf** [comment]
Day night switch was added to all boards. This issue should be solved.

**Comment by EERCrso** [comment]
este nie je naprogramovany

**Comment by xosuskyf** [comment]
tuto je to zmienene, nemam zariadenie na testovanie, inak by som to skusil a dal zelenu na pull request.
https://github.com/vtothsvk/AP-Home/issues/64

**Comment by EERCrso** [comment]
jaj ok
