### ISSUE TITLE
different position for mute button

### ISSUE THREAD

**Issue by EERCrso** [vtothsvk/AP-Home#24]
**Is your feature request related to a problem? Please describe.**
Possible risk of switching day night switch then mute button is in vicinity of switch

**Describe the solution you'd like**
I would suggest to  move move button on the top of the box to be:
1) clearly visible
2) easy to push with palm of the hand
3) low risk of pushing other buttons on the sides of the  sensor case

**Comment by xmirob** [comment]
We should discuss this.

**Comment by EERCrso** [comment]
ok štvrtok teda

**Comment by xosuskyf** [comment]
@xmirob suggested not to put anything on the sensor boar lid due to the cable management within the casing and potential issue related with that.

**Comment by EERCrso** [comment]
done
