### ISSUE TITLE
Senzor board case and bracelet board case are too transparent

### ISSUE THREAD

**Issue by EERCrso** [vtothsvk/AP-Home#25]
**Describe the bug**
 the material and its color are too transparent. All diods shine outside. This can be :
1) distracting for patients
2) misleading if there is an problem or not
3) its ugly

![image](https://user-images.githubusercontent.com/66819699/98520148-f1e68f80-2271-11eb-932b-2eab9b3ef8d9.png)

I would suggest:
1) try to print from materials that block more light
2) use color spray. spray the box from inside
3) dim the LEDs

**Comment by xmirob** [comment]
LEDs must be dimmed or removed.

**Comment by EERCrso** [comment]
presunute https://github.com/vtothsvk/AP-Home/issues/43#issue-739832435 a zatvaram
