### ISSUE TITLE
Bracellet board cannot be inserted into the case

### ISSUE THREAD

**Issue by EERCrso** [vtothsvk/AP-Home#27]
**Describe the bug**
Bracelet board with batteries,  dildo ( vibrator ) is too big for the casing

**Comment by xosuskyf** [comment]
We still not have correct holder for batteries, however, I optimized the space inside a little bit and all the components can fit. See picture.
![1604913110713](https://user-images.githubusercontent.com/73240403/98521828-44c14680-2274-11eb-928f-46ac60da05d0.jpg)

**Comment by EERCrso** [comment]
ok  great

**Comment by EERCrso** [comment]
According the answer issue was fixed
