### ISSUE TITLE
PIR sensor saturation.

### ISSUE THREAD

**Issue by vtothsvk** [vtothsvk/AP-Home#31]
**Describe the bug**
PIR sensor gets saturated in daylight.

**Additional context**
Do we have a solution? @mato24101 can we make smth about it from HW point of view? @xosuskyf other PIR sensor (eg. the M5Stack ones) or some other solution?

**Comment by xosuskyf** [comment]
PIR dedicated for waspomte technology (Paralax 555-28027) is working like a charm, however the casing does not have proper opening for this sensor and also this sensor is huge 2.5x3.5x2.5 cm.
![1606289595662](https://user-images.githubusercontent.com/73240403/100196696-87805100-2ef9-11eb-8710-270f3a80b598.jpg)

**Comment by vtothsvk** [comment]
@xosuskyf možno blbosť, ale skúsil sa už aj iný kus z tých PIR-ov, čo sa pôvodne na Home používali? 😅

**Comment by xosuskyf** [comment]
Skusil som 3 rozne

**Comment by EERCrso** [comment]
PIR ktory dodal filip najnovsi je  v poriadku  Uzatvaram
