### ISSUE TITLE
Sensor enable

### ISSUE THREAD

**Issue by vtothsvk** [vtothsvk/AP-Home#32]
**Is your feature request related to a problem? Please describe.**
Need to add a mechanism to enable/disable given sensor reading

**Describe the solution you'd like**
A directive toggle header.

**Describe alternatives you've considered**
Nothing else comes to my mind. Nothing that will solve the issue this fast

**Comment by vtothsvk** [comment]
@EERCrso @xosuskyf pridal som potom `_ENABLE` direktívy na ovládanie readu aj ostatných senzorov do **Sensor_enale.h** tak by bolo fasa keby to testnete. Je to v [main](https://github.com/vtothsvk/AP-Home)e v posledom commite.

**Comment by EERCrso** [comment]
Ja to zajtra rano určite testnem

**Comment by EERCrso** [comment]
Vsetko funguje
