### ISSUE TITLE
Problem s parovanim bez alertu na bracellet board

### ISSUE THREAD

**Issue by EERCrso** [vtothsvk/AP-Home#42]
**Describe the bug**
Hodinky sa nesparuju pokial nie je alert

**To Reproduce**
Steps to reproduce the behavior e.g.:
zapni senzos board
bracelet bord sa zapne a nevydáva alert
zapni hodinky
hodinky sa nesparuju nikdy
vyvolaj alert
hodinky sa az nasledne sparuju

**Expected behavior**
sparovanie vzdy aj bracelet board nevydava alert

**Comment by vtothsvk** [comment]
Jop, ono je to tým, že encoder spí (neposiela správy) kým nedôjde k zmene statusu. Čo znamená, že prvú správu vyšle až keď nastane prvý alert.

Possible fix:
1. Párovacie okno pri zapnutí boardu
2. Periodické vyslanie správy

Spravím kód pre oba prípady a uvidíme, ktorý vyjde lepšie.

**Comment by xosuskyf** [comment]
Pod prvym krokom "zapni bracelet board" myslis asi sensor board, lebo nikde v krokoch nespustame senzoricku dosku.
To, ze sa to teraz nesparuje je asi kvoli tomu, ze TE pin teraz nevysiela stale a iba pri zmenach. Overime.

**Comment by vtothsvk** [comment]
Nahodil som tam nakoniec aj aj. Tj. keď sa device zapne je tam 5s okno, kedy posiela správy jak divý nech sa spáruje a pak sa ešte každých 5s ozve, keby náhodou spojenie vypadlo/v prípade resetu hodiniek netrebalo fiurt aj krabicu resetovať.

Pridal som to posledným mergeom do [main](https://github.com/vtothsvk/AP-Home)u ([#45](https://github.com/vtothsvk/AP-Home/pull/45)).

**Comment by EERCrso** [comment]
ano tak som to myslel.... ako si pisal FIlip..... otestovane. FUnguje to len v pripade ak je zariadenie pripojene k PC a sledujem monitor v opačnom pripade nie..  deje sa nasledovne:
sensor board odpojeny od PC
- zapnem bracellet board
- zapnej hodinky.. hodinky su nesparovane svietia dve diodi a vrčia jak dive
- po chvili zasvieti len jedna dioda a vrčia menej

**Comment by vtothsvk** [comment]
Bol inicializovaný len jeden pin Encoderu, fixol som to posledným pushom, je to na maine. Čím môže byť, že to funguje len keď to máš pripojené si nie som istý. Skús teraz uvidíš čo to spraví.

**Comment by xosuskyf** [comment]
hm, nema @EERCrso porbelm s tym, ze maju to iba pripojene na kabli, bez hlavneho napajanie, ako sme to mali predtym, ked tie ostcilacne frekvencie, kvoli znizeniu napatia na baterkach nesedeli? Ake mate @EERCrso napatie na oboch bateriach?

**Comment by EERCrso** [comment]
Chybaju tam nejake subory nato aby to skusil 
![image](https://user-images.githubusercontent.com/66819699/99234866-6632ad00-27f5-11eb-87e8-798a80f1a3dd.png)

**Comment by EERCrso** [comment]
Filip ne tam problem neni

**Comment by vtothsvk** [comment]
@EERCrso mea culpa, som vás zabudol upozorniť, že som aktualizoval setup prostredia.
Checknite [dokumentáciu](https://github.com/vtothsvk/AP-Home/blob/main/Documentation/Programming.md) konkrétne **Install dependecies**
Potrebujete si nainštalovať knižnice pre bme280
(@xosuskyf pls checkni tiež)

**Comment by EERCrso** [comment]
Jo dakujem.. stale to nefunguje hodinky sa paruju ale miesto toho aby sa uhludnili zacne svietit len jedna dioda a menej vybrovat.. to iste ked odpojim debug a mam ich len na napajani

**Comment by EERCrso** [comment]
neveim ci to nazvat vobec sparovanie..... tento problem je aj cez debug aj bez debug

**Comment by vtothsvk** [comment]
Sry blbo som mergol jeden pull request. Posledným mainom by to malo ísť.

**Comment by EERCrso** [comment]
Uz to ide, testovane teraz na mojom PC (MC).
