### ISSUE TITLE
DIM LED

### ISSUE THREAD

**Issue by EERCrso** [vtothsvk/AP-Home#43]
**Describe the bug**
Potrebujeme DImoval LED lebo nam to moc svieti z vnutra von
https://github.com/vtothsvk/AP-Home/issues/25#issue-738832882

**Comment by vtothsvk** [comment]
@EERCrso začierni ich centrofixkou zatiaľ. Mne to zvykáva pomôcť :) . @

**Comment by EERCrso** [comment]
ok bude sa to čierniť
