### ISSUE TITLE
Redundant repo branches

### ISSUE THREAD

**Issue by vtothsvk** [vtothsvk/AP-Home#48]
@xosuskyf Zdar, potrebuješ [testing_device1](https://github.com/vtothsvk/AP-Home/tree/testing_device1) branch na remote? ak nie tak ho pls zmaž lebo je chudák 54 commitov za mainom, neviem, či na ňom toho veľa otestuješ 😄. (poprípade ti doň pullnem update z mainu ak ho chceš mať na remote 😉)

**Comment by xosuskyf** [comment]
Done

**Comment by vtothsvk** [comment]
thx 👍
