### ISSUE TITLE
M5Stack PIR Senzor

### ISSUE THREAD

**Issue by vtothsvk** [vtothsvk/AP-Home#57]
Zdravím páni, 
problém: M5Stack PIR senzory nie su skladom, resp. nie tie čo sa objednávali, majú ich už len v prevedení [HAT](https://m5stack.com/collections/m5-hat/products/m5stickccompatible-hat-pir-sensor) Tak otázka je, či ich chceme, za mňa áno, si myslím, že takto to bude ešte lepšie, lebo sa netreba drbať s káblom ale bol by som rád keby ste sa ASAP vyjadrili.
Thx.

**Comment by vtothsvk** [comment]
Bump

**Comment by xosuskyf** [comment]
Za mna je to ok, ked to viete spojazdnit na m5stackoch. Rozhodne treba PIRka nakupit.

**Comment by vtothsvk** [comment]
tak keďže má @mato24101 u prdeli tak som povedal, nech sa objednajú a zatváram issue 😄
