### ISSUE TITLE
Unable to Pair bracelet board and sensor board + strange behaviour

### ISSUE THREAD

**Issue by EERCrso** [vtothsvk/AP-Home#63]
**Describe the bug**
Hodinky nejde sparovat +  spravaju sa zvlastne popis v To reproduce

**To Reproduce**
Steps to reproduce the behavior e.g.:
Nahral som na bracelet board najnovsi firmware
spustim zariadenie
neparuje 
resetoval som senzor board mnohonasobne a nikdy sa nesparuju
Niekedy hned po resete prestane bracelet borad vybrovat a vtedy mam pocit že sa sparoval ale nie je to tak ked potom vytovrim alert napriklad pressure senzorom tak hodinky nereaguju a nevybruju

**Expected behavior**
ze sa sparuju

**Evironment:**
 - OS: [e.g. Windows 10]
 - IDE used and its version (e.g. VSCode 1.48.2 with Arduino IDE 1.8.9)
 - Compiler toolchain and version (xtensa-lx106-elf-gcc )
 - Hash of the commit used or at least the branch/tag ( https://github.com/vtothsvk/AP-Home/commit/9783c2de9a46e4b60074e002fa2119b8dc4565a0)
)

**Comment by EERCrso** [comment]
Je to divne  asi po hodine som vsetko zopakoval a sparovalo hodinky  v pripade že som nebol pripojeni k PC

**Comment by xosuskyf** [comment]
Zmerajte napatie na baterkach. Mozno uz moc kleslo a zacina to blbnut. Toto mozno bude dobre aj zdokumentovat ako hranicnu podmienku parovania. Mne fungovali vsetky zariadenia v piatok, co sa tyka parovania s tymto braceletom.

**Comment by EERCrso** [comment]
napätie je 5.8 V ... momentalne paruju ...

**Comment by EERCrso** [comment]
dnes opat paruju zatvaram ked sa zopakuje otvorim
