### ISSUE TITLE
timer after Mute triggered

### ISSUE THREAD

**Issue by EERCrso** [vtothsvk/AP-Home#74]
**Is your feature request related to a problem? Please describe.**
Aby nedošlo k tomu že mutnem board ale kedže som pred motion tak mi tregerrne error..

**Describe the solution you'd like**
bolo by vhodne vediet nastavit čas počas ktoreho po stlačeni mute buttu budu všetky alerty ignorovane. Toto nastavenie je  potrebne pre night/ day režim

**Comment by vtothsvk** [comment]
```
/** Alert control directives
 */
#define muteDuration    2000
```
ste si asi nevšimli.

**Comment by EERCrso** [comment]
Aha prepač nevšimli... je to v mili sekundach ?  Ale moc to nejde... nastavil som  20 000 spustil alert stlačil gombik .. alert zmizol za chvilu ( ale asi nie koli gombiku ) a hned som mohol trierrnut dalši

**Comment by vtothsvk** [comment]
Ale predpokladám, že máte pustený printout, vtedy button nefunguje, lebo mu to breakne časovanie.

**Comment by vtothsvk** [comment]
@EERCrso skúsili, ste btw. či hodnotu buttonu číta správne?

**Comment by vtothsvk** [comment]
Mne to meria správnu hodnotu na danom pine, bol tam ale malý zádrheľ, a síce button handler bol zle inicializovaný, testol som s káblikom a hralo všetko ako má. Kód najdete na [buttonFix](https://github.com/vtothsvk/AP-Home/tree/buttonFix) (https://github.com/vtothsvk/AP-Home/pull/77)

**Comment by EERCrso** [comment]
čo mysliš pod print out ? printout  toto ?  //#define _DEBUG  ?  Nechal som zakomentovane a po stlačeni buttnu nedojde k zmene statusu ani pri jednej polohe switch

ked si zobrazim vypis  a ked stlačim button tam vo vypise mam jednotku...

**@EERCrso skúsili, ste btw. či hodnotu buttonu číta správne?**   Ako to mame skusiť ?

**Comment by vtothsvk** [comment]
> **@EERCrso skúsili, ste btw. či hodnotu buttonu číta správne?** Ako to mame skusiť ?
takto
> ked si zobrazim vypis a ked stlačim button tam vo vypise mam jednotku...

Ono inak to trochu pomalšie reaguje treba nechať to tlačítko takú dobrú polsekundu, možno aj sekundu stlačené, kým to zareaguje btw.

**Comment by EERCrso** [comment]
Bohužial .. skusil som prave ako vraviš.. a nič stale je alert aj ked dlho aj ked par sekund podržim ... vypis nemam aktivovany.... pozeram sa len na serial monitor či mi nebude vyhadzovať same nuly...

**Comment by vtothsvk** [comment]
no keby nemáš aktivovaný výpis tak by to nemalo písať nič, iba, že sa nabootovalo

**Comment by vtothsvk** [comment]
@EERCrso mali by ste čas na chvíľu s tým deviceom dobehnúť, že by som sa naň pozrel?

**Comment by EERCrso** [comment]
@vtothsvk ideme za tebou

**Comment by vtothsvk** [comment]
Tak teda funguje na 2 kliky 😅
