### ISSUE TITLE
Button pin died

### ISSUE THREAD

**Issue by vtothsvk** [vtothsvk/AP-Home#8]
**Describe the bug**
Button pin died. We don't know if it was caused by the board or the pin was already dead during the board testing.

**To Reproduce**
1. Check if the pin is working before testing the board
2. flash buttonTest
3. Let the node boot
4. Measure Button pin output
5. Enable driving the Button pin HIGH during boot by uncommenting ` //#define _BUTTON_TEST`
6. Let the node boot
7. Measure Button pin output

**Expected behavior**
If the HW is not at fault, during the 1st measurement the pin will be LOW and during the second it will be HIGH.

**Comment by vtothsvk** [comment]
Bump

**Comment by xosuskyf** [comment]
ked dam git checkout buttonTest a potom git pull tak to vypise toto. (dal som predtym stash na ten kod co som mal akoze ja)

There is no tracking information for the current branch.
Please specify which branch you want to merge with.

pri ostatnych branchoch mi to v pohode stiahne danu verziu, prikaz git pull, pri tomto to vypise to vyssie.

**Comment by vtothsvk** [comment]
pravdepodobne nie si v spravnom adresari

**Comment by vtothsvk** [comment]
skus tieto veci skontrolovat ak nepomoze tak som o par min doma a kuknem na to

**Comment by vtothsvk** [comment]
este ked tak skus git fetch a pak git pull

**Comment by xosuskyf** [comment]
pri kompilacii buttonTest

AP-Home:98:9: error: 'button' was not declared in this scope

     if((button.clicks == 1)){

         ^

exit status 1
'button' was not declared in this scope

taktiez na riadku 63 button.Update();

oboje som vykomentoval a uz to ide skompilovat

**Comment by xosuskyf** [comment]
v oboch pripadoch napatie 3.28 V, je to nova doska, kde button nebol pripojeny

**Comment by vtothsvk** [comment]
> v oboch pripadoch napatie 3.28 V, je to nova doska, kde button nebol pripojeny

dobre, vyskúšal si ten pin mimo dosky? či keď má byť low tak je low a keď high tak high? (vieš, že či ten GPIO vieme ovládať vôbec aj keď sme to skúšali, ale nikdy nevieš)

**Comment by xosuskyf** [comment]
ano skusal som to mimo dosky, ale mozno tym, ze to ESP bolo pripojene uz predtym na PCB dosku, kedze som testoval senzory, tak nie som si isty, ci uz ten pin nebol predtym odpaleny. Asi treba skusit naflashovat buttonTest na novu dosku, ktora nikdy nebola pripojena na PCB aby sme otestovali moznost ovladania pinu

**Comment by vtothsvk** [comment]
Suhlasim.

**Comment by EERCrso** [comment]
toto je aky button? Day/night alebo mute button ?

**Comment by vtothsvk** [comment]
Nie, D/N je prepínač

**Comment by xosuskyf** [comment]
kedze cely cas mame problem s tlacidlom vedla day/night prepianaca (takze ten mute button, v kode nazvany utility button, v D.T2.3 sprave nazvany programmable event button), tak to tlacidlo vedla testujem. Pin na tento button sme pravdepodobne odpalili pri prvej doske. Jedna sa o RX pin (D9, GPIO3). Aj v tasku je napisane, ze nevieme, co sposobilo, ze ten pin nie je odpaleny a ja nemam vedomost ze sme nieco riesli s day/night prepinacom. Ak mam riesit day/night prepinac, napiste.

Na uplne novej doske som nahral buttonTest kod a v oboch pripadoch testovania mi to dava hodnotu 3.28 V na RX pine (high). Musel som vykomentovat if z riadku 98 a buttonupdate z riadku 63. Prosim, @vtothsvk mozes skontrolvat, ci tym vykomentovanim som nieco nedodrbal a stale sa mal pin spravat pocas testu ako si uviedol v zadani?

Dakujem

**Comment by vtothsvk** [comment]
S tym odkomentovanim si nemohol nič dodrbať, problém bude v samotnom core, keďže inicializuje RX pin na komunikáciu po sériovom porte, ktorý je na USB-čku. Čo je ale fest divné, že je pull-upnutý. Z mne neznámeho dôvodu je inicializovaný v open drain konfigurácii, čo mi pri UART-e v celku nedáva zmysel. Hrabem sa teraz v core a snažím sa to ohackovať. Ak sa mi niečo podarí dám update.

**Comment by vtothsvk** [comment]
Dá sa to ohackovať, v prípade, že vyhodím celú inicializáciu Serial portu, čo znamená, že sa v takom prípade s nami doska nebude vedieť rozprávať cez USB. Príde mi to teraz ale ako bullshit, nakoľko sme to skúšali na sucho a všetko fičalo...

No nič @mato24101 máme tam ešte dajaký voľný pin?

**Comment by xosuskyf** [comment]
Otazka znie, ci teda ten pin je funkcny pri sucasnom dizajne PCB boardu a staci len ohackovat ten pin po finalizacii produktu?

**Comment by vtothsvk** [comment]
jop, ale sa akosi @mato24101 nevyjadril 😄

**Comment by mato24101** [comment]
Ospravedlňujeme sa že som vám neodpísal ale teda voľné piny máme D10/GPIO1, D8/GPIO15, D12/GPIO10, D11/GPIO9 viem že niektoré z nich nieje možné využívať (myslím že D11 a D12) takže ak vieme skontrolovať či napríklad D10 nemá rovnaký problém tak to vieme v podstate jednoducho zmeniť

**Comment by vtothsvk** [comment]
D8/GPIO15 by sme hypoteticky vedeli použiť, idem to testnúť.

**Comment by vtothsvk** [comment]
Na D8 to nemá žiaden problém? @mato24101 neplánovali sme to aj pôvodne dať tam 😅 ?

**Comment by xosuskyf** [comment]
bump

**Comment by EERCrso** [comment]
čo znamena bump ?

**Comment by vtothsvk** [comment]
> čo znamena bump ?

bump je dummy správa/comment ktorá sa používa na pripomenutie konverzácie, v podstate taký poke, aby na to zapojení ľudia nezabudli

**Comment by mato24101** [comment]
Takže odrezať stávajú u cestu a káblik na D8 hej?

**Comment by vtothsvk** [comment]
> Takže odrezať stávajú u cestu a káblik na D8 hej?

áno

**Comment by vtothsvk** [comment]
@mato24101 už hackol.
