### ISSUE TITLE
No space for the NOICE sensor borad

### ISSUE THREAD

**Issue by xosuskyf** [vtothsvk/AP-Home#84]
There is no space of the noice sensor board in V4 version of casing. The board of noice sensor (green elipse) is blocked by the lid frame (red elipse).

1. Put the NOISE sensor in its place.
2. Try to close the lid.

Remove additional material of the lid frame (blue elipse) to be able to fit the sensor

![1607337906490_b](https://user-images.githubusercontent.com/73240403/101358631-6a556600-389b-11eb-9caf-a107e4799ef6.jpg)
![1607337906482_b](https://user-images.githubusercontent.com/73240403/101358649-6e818380-389b-11eb-90f3-d90a8023cf8a.jpg)
![1607337906473_b](https://user-images.githubusercontent.com/73240403/101358658-72ada100-389b-11eb-980a-4a476004687c.jpg)

**Comment by EERCrso** [comment]
noise senzor odstraneny
