### ISSUE TITLE
Day/night switch does not fit into the prepared opening in the casing.

### ISSUE THREAD

**Issue by xosuskyf** [vtothsvk/AP-Home#85]
Day/night switch does not have proper hole. Increase the hole radius of the hole at least 2 mm (please test it with real day/night switch) and relocate whole hole up and closer to the casing lid approximately 5 mm (currently the placement of the day/night switch is blocked by the sensor board PCB board).

To reproduce:
1. Try to put the day/night switch into the correct hole highlighted with red ellipse in the picture.
2. Try to put the day/night switch to the increased sized hole when whole PCB sensor board is inserted in the casing.
![1607337906505_c](https://user-images.githubusercontent.com/73240403/101359353-6d048b00-389c-11eb-8bdc-544a098b3435.jpg)

**Comment by EERCrso** [comment]
done
