### ISSUE TITLE
Small PIR sensor hole

### ISSUE THREAD

**Issue by xosuskyf** [vtothsvk/AP-Home#87]
The hole for the new PIR sensor is small (red ellipse). 

1. Take PIR 312 module.
2. Remove all PIR heat diffusers.
3. Try to stick it through the prepared hole.

Increase the diameter of the hole at least to 10.61 mm.
![1607337906498_e](https://user-images.githubusercontent.com/73240403/101360458-f5cff680-389d-11eb-8e5f-de4e387a20ea.jpg)

**Comment by EERCrso** [comment]
vyriešene
